//
//  ProviderCatalog.swift
//  Agenic Load-Balancer
//
//  Created by OpenAI Codex on 5/5/26.
//

import Foundation

enum ProviderCatalog {
    static let defaultProfiles: [AgentProviderDraft] = [
        AgentProviderDraft(
            identifier: "openai.codex",
            displayName: "Codex CLI",
            providerFamily: "OpenAI",
            homepageURL: "https://developers.openai.com/codex/cli",
            sourceURL: "https://developers.openai.com/codex/cli",
            binaryName: "codex",
            installCommand: "npm install -g @openai/codex",
            verificationCommand: "codex --version",
            authGuide: "Use ChatGPT sign-in or configure an OpenAI API key through Codex CLI settings.",
            authMethods: "ChatGPT login,API key",
            capabilities: "code-editing,review,debugging,local-workspace,streaming-json,model-selection",
            supportedExecutionModes: [
                AgentExecutionMode.recommendOnly,
                .readReview,
                .planOnly,
                .implementation,
                .repairDebug,
                .testBuild,
                .commitPushCheckpoint,
            ].map(\.rawValue).joined(separator: ","),
            modelListSource: "Codex CLI profiles and OpenAI account entitlements.",
            costPolicySummary: "Track observed runs; use user-entered subscription/API policy for estimates.",
            quotaPolicySummary: "Track observed session pressure and user-configured plan limits.",
            safetyNotes: "Requires explicit approval before implementation or commit/push dispatch."
        ),
        AgentProviderDraft(
            identifier: "anthropic.claude-code",
            displayName: "Claude Code",
            providerFamily: "Anthropic",
            homepageURL: "https://code.claude.com/docs/en/authentication",
            sourceURL: "https://code.claude.com/docs/en/authentication",
            binaryName: "claude",
            installCommand: "npm install -g @anthropic-ai/claude-code",
            verificationCommand: "claude --version",
            authGuide: "Use Claude subscription login, Anthropic API key, or supported cloud-provider auth.",
            authMethods: "Browser login,API key,cloud provider",
            capabilities: "code-editing,review,debugging,local-workspace,agents,stream-json,model-selection",
            supportedExecutionModes: [
                AgentExecutionMode.recommendOnly,
                .readReview,
                .planOnly,
                .implementation,
                .repairDebug,
                .testBuild,
                .commitPushCheckpoint,
            ].map(\.rawValue).joined(separator: ","),
            modelListSource: "Claude Code CLI and Anthropic account entitlements.",
            costPolicySummary: "Track observed subscription/API use and user-entered budget policy.",
            quotaPolicySummary: "Track observed session limits, reset windows, and provider throttles.",
            safetyNotes: "Supports powerful tools; show allowed-tool scope before dispatch."
        ),
        AgentProviderDraft(
            identifier: "github.copilot-cli",
            displayName: "GitHub Copilot CLI",
            providerFamily: "GitHub",
            homepageURL: "https://docs.github.com/en/copilot/how-tos/copilot-cli/cli-getting-started",
            sourceURL: "https://cli.github.com/manual/gh_copilot",
            binaryName: "gh",
            installCommand: "brew install gh && gh copilot -- --help",
            verificationCommand: "gh copilot -- --help",
            authGuide: "Authenticate GitHub CLI, then use the preview Copilot CLI path or install Copilot CLI.",
            authMethods: "GitHub login,Copilot subscription",
            capabilities: "code-review,shell-help,local-workspace,preview-cli",
            supportedExecutionModes: [
                AgentExecutionMode.recommendOnly,
                .readReview,
                .planOnly,
                .repairDebug,
                .testBuild,
            ].map(\.rawValue).joined(separator: ","),
            modelListSource: "GitHub Copilot CLI capabilities and account entitlement.",
            costPolicySummary: "Track observed calls; Copilot subscription limits are user-configured.",
            quotaPolicySummary: "Track throttles and manual subscription policy.",
            safetyNotes: "The `gh copilot` path is preview; require visible command confirmation."
        ),
        AgentProviderDraft(
            identifier: "google.gemini-cli",
            displayName: "Gemini CLI",
            providerFamily: "Google",
            homepageURL: "https://github.com/google-gemini/gemini-cli/blob/main/docs/get-started/index.md",
            sourceURL: "https://github.com/google-gemini/gemini-cli",
            binaryName: "gemini",
            installCommand: "npm install -g @google/gemini-cli",
            verificationCommand: "gemini --version",
            authGuide: "Use Google account or API key setup supported by Gemini CLI.",
            authMethods: "Google login,API key",
            capabilities: "code-editing,review,debugging,local-workspace,model-selection",
            supportedExecutionModes: [
                AgentExecutionMode.recommendOnly,
                .readReview,
                .planOnly,
                .implementation,
                .repairDebug,
                .testBuild,
            ].map(\.rawValue).joined(separator: ","),
            modelListSource: "Gemini CLI configuration and Google account entitlements.",
            costPolicySummary: "Track observed API/subscription use and user-entered cost policy.",
            quotaPolicySummary: "Track request throttles and user-configured reset windows.",
            safetyNotes: "Use implementation mode only after explicit approval."
        ),
        AgentProviderDraft(
            identifier: "cursor.agent",
            displayName: "Cursor Agent",
            providerFamily: "Cursor",
            homepageURL: "https://cursor.com",
            sourceURL: "https://cursor.com",
            binaryName: "cursor-agent",
            installCommand: "Install Cursor Agent from the official Cursor distribution, then verify `cursor-agent --version`.",
            verificationCommand: "cursor-agent --version",
            authGuide: "Use Cursor account login or API key flow supported by the official agent.",
            authMethods: "Browser login,API key",
            capabilities: "code-editing,review,debugging,local-workspace,model-selection",
            supportedExecutionModes: [
                AgentExecutionMode.recommendOnly,
                .readReview,
                .planOnly,
                .implementation,
                .repairDebug,
                .testBuild,
            ].map(\.rawValue).joined(separator: ","),
            modelListSource: "Cursor Agent settings and provider entitlements.",
            costPolicySummary: "Track observed usage and user-entered Cursor/model policy.",
            quotaPolicySummary: "Track observed limits and manual subscription settings.",
            safetyNotes: "Provider command is configurable because published CLI behavior can vary by channel."
        ),
        AgentProviderDraft(
            identifier: "kiro.cli",
            displayName: "Kiro CLI",
            providerFamily: "Kiro / Amazon Q",
            homepageURL: "https://kiro.dev/docs/cli/installation/",
            sourceURL: "https://kiro.dev/docs/cli/migrating-from-q/",
            binaryName: "kiro",
            installCommand: "Follow the official Kiro CLI installer, then verify `kiro --version` or compatible `q --version`.",
            verificationCommand: "kiro --version",
            authGuide: "Use browser auth through GitHub, Gmail, Builder ID, or IAM Identity Center as supported.",
            authMethods: "Browser login,Builder ID,IAM Identity Center",
            capabilities: "code-review,planning,local-workspace,cloud-provider-auth",
            supportedExecutionModes: [
                AgentExecutionMode.recommendOnly,
                .readReview,
                .planOnly,
                .repairDebug,
                .testBuild,
            ].map(\.rawValue).joined(separator: ","),
            modelListSource: "Kiro CLI account and provider configuration.",
            costPolicySummary: "Track observed calls and user-entered account policy.",
            quotaPolicySummary: "Track observed session limits, throttles, and reset windows.",
            safetyNotes: "Support both Kiro and legacy Amazon Q command discovery where present."
        ),
        AgentProviderDraft(
            identifier: "qwen.code",
            displayName: "Qwen Code",
            providerFamily: "Alibaba Cloud / Qwen",
            homepageURL: "https://github.com/QwenLM/qwen-code",
            sourceURL: "https://github.com/QwenLM/qwen-code",
            binaryName: "qwen",
            installCommand: "npm install -g @qwen-code/qwen-code",
            verificationCommand: "qwen --version",
            authGuide: "Use supported API key or coding-plan authentication.",
            authMethods: "API key,Coding Plan",
            capabilities: "code-editing,review,debugging,local-workspace",
            supportedExecutionModes: [
                AgentExecutionMode.recommendOnly,
                .readReview,
                .planOnly,
                .implementation,
                .repairDebug,
                .testBuild,
            ].map(\.rawValue).joined(separator: ","),
            modelListSource: "Qwen Code CLI configuration.",
            costPolicySummary: "Track observed API usage and user-entered plan policy.",
            quotaPolicySummary: "Track observed throttles and manual reset windows.",
            safetyNotes: "Use configurable auth because OAuth availability changes by provider policy."
        ),
        AgentProviderDraft(
            identifier: "mistral.vibe",
            displayName: "Mistral Vibe",
            providerFamily: "Mistral",
            homepageURL: "https://docs.mistral.ai/mistral-vibe/terminal",
            sourceURL: "https://docs.mistral.ai/mistral-vibe/terminal",
            binaryName: "vibe",
            installCommand: "Install Mistral Vibe from the official terminal documentation, then verify `vibe --version`.",
            verificationCommand: "vibe --version",
            authGuide: "Use Mistral-supported account/API authentication.",
            authMethods: "API key,Browser login",
            capabilities: "code-editing,review,debugging,local-workspace,search",
            supportedExecutionModes: [
                AgentExecutionMode.recommendOnly,
                .readReview,
                .planOnly,
                .implementation,
                .repairDebug,
                .testBuild,
            ].map(\.rawValue).joined(separator: ","),
            modelListSource: "Mistral Vibe configuration.",
            costPolicySummary: "Track observed usage and user-entered Mistral cost policy.",
            quotaPolicySummary: "Track provider throttles and manual limit windows.",
            safetyNotes: "Provider setup remains command-preview only until verified locally."
        ),
        AgentProviderDraft(
            identifier: "opencode.cli",
            displayName: "OpenCode",
            providerFamily: "OpenCode",
            homepageURL: "https://dev.opencode.ai/docs/",
            sourceURL: "https://dev.opencode.ai/docs/",
            binaryName: "opencode",
            installCommand: "Install OpenCode from the official docs, then verify `opencode --version`.",
            verificationCommand: "opencode --version",
            authGuide: "Use `/connect`, provider API keys, or custom provider configuration.",
            authMethods: "API key,provider connection,custom",
            capabilities: "code-editing,review,debugging,local-workspace,multi-provider,deepseek-api",
            supportedExecutionModes: [
                AgentExecutionMode.recommendOnly,
                .readReview,
                .planOnly,
                .implementation,
                .repairDebug,
                .testBuild,
            ].map(\.rawValue).joined(separator: ","),
            modelListSource: "OpenCode provider configuration.",
            costPolicySummary: "Use provider-specific manual/API policy and observed usage.",
            quotaPolicySummary: "Track observed throttles and configured provider windows.",
            safetyNotes: "Good fallback path for DeepSeek and other API-only providers."
        ),
        AgentProviderDraft(
            identifier: "apple.foundation-models",
            displayName: "Apple Foundation Models",
            providerFamily: "Apple",
            homepageURL: "https://developer.apple.com/documentation/foundationmodels",
            sourceURL: "https://developer.apple.com/documentation/foundationmodels",
            binaryName: "in-process",
            installCommand: "Built into macOS 26+. Enable Apple Intelligence in System Settings → Apple Intelligence & Siri.",
            verificationCommand: "Probed via SystemLanguageModel.default.availability inside the app.",
            authGuide: "Uses on-device Apple Intelligence — no API key, no network call. Verify Apple Intelligence is enabled for the user.",
            authMethods: "On-device,Apple Intelligence",
            capabilities: "code-editing,review,debugging,local-workspace,structured-generation,tool-calling,private-on-device",
            supportedExecutionModes: [
                AgentExecutionMode.recommendOnly,
                .readReview,
                .planOnly,
                .implementation,
                .repairDebug,
                .testBuild,
            ].map(\.rawValue).joined(separator: ","),
            modelListSource: "On-device system model published by Apple Intelligence; one logical model per device.",
            costPolicySummary: "No per-call cost. Inference is on-device and free.",
            quotaPolicySummary: "Throttled by device thermal/power state. Tokens-per-second varies by hardware generation.",
            safetyNotes: "Privacy-preserving: prompts and outputs never leave the device."
        ),
        AgentProviderDraft(
            identifier: "deepseek.api",
            displayName: "DeepSeek API",
            providerFamily: "DeepSeek",
            homepageURL: "https://api-docs.deepseek.com/guides/coding_agents",
            sourceURL: "https://api-docs.deepseek.com/guides/coding_agents",
            binaryName: "custom",
            installCommand: "Configure DeepSeek through OpenCode, a compatible CLI, or a custom command profile.",
            verificationCommand: "Custom profile verification command required",
            authGuide: "Store API key in Keychain and sync only the credential reference.",
            authMethods: "API key,custom command",
            capabilities: "api-provider,code-generation,custom-command,opencode-compatible",
            supportedExecutionModes: [
                AgentExecutionMode.recommendOnly,
                .readReview,
                .planOnly,
                .implementation,
                .repairDebug,
            ].map(\.rawValue).joined(separator: ","),
            modelListSource: "DeepSeek API docs and custom provider settings.",
            costPolicySummary: "Use API pricing policy configured by user; track observed calls.",
            quotaPolicySummary: "Track provider-reported errors and manual limits.",
            safetyNotes: "No first-party standalone coding CLI is assumed for v1."
        ),
    ]
}
